############################################################################################
# Trading Engine YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Only 1 engine block can be specified.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
############################################################################################
---
engine:

  # A unique identifier for the bot. Value must be an alphanumeric string.
  # Underscores and dashes are also permitted. E.g. my-bitstamp-bot_1
  botId: my-ta4j-backtest-bot

  # A friendly name for the bot. Value must be an alphanumeric string. Spaces are allowed. E.g. Bitstamp Bot
  botName: TA4J Backtest Bot

  # This must be set to prevent catastrophic loss on the exchange.
  # This is normally the currency you intend to hold a long position in. It should be set to the currency short code
  # for the wallet, e.g. BTC, LTC, USD. This value can be case sensitive for some exchanges - check the Exchange Adapter
  # documentation.
  emergencyStopCurrency: ZEUR

  # This must be set to prevent a catastrophic loss on the exchange.
  # The Trading Engine checks this value at the start of every trade cycle: if your emergencyStopCurrency balance on
  # the trading drops below this value, the Trading Engine will stop trading on all markets and shutdown.
  # Manual intervention is then required to restart the bot. You can set this value to 0 to override this check.
  emergencyStopBalance: 50.0

  # The is the interval in seconds that the Trading Engine will wait/sleep before executing
  # the next trade cycle. The minimum value is 1 second. Some exchanges allow you to hit them harder than others.
  # However, while their API documentation might say one thing, the reality is you might get socket timeouts and 5XX
  # responses if you hit it too hard - you cannot perform ultra low latency trading over the public internet ;-)
  # You'll need to experiment with the trade cycle interval for different exchanges.
  tradeCycleInterval: 0
