############################################################################################
# Email Alerts YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Only 1 emailAlerts block can be specified.
# - The email is sent using TLS.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# Sample config for using a Gmail account to send the email is shown below.
############################################################################################
---
emailAlerts:

  # If set to true, the bot will load the smtpConfig, and enable email alerts.
  enabled: false

  # Set your SMTP details here.
  smtpConfig:
    host: smtp.gmail.com
    tlsPort: 587
    accountUsername: your.account.username@gmail.com
    accountPassword: your.account.password
    fromAddress: from.addr@gmail.com
    toAddress: to.addr@gmail.com

